### ISSUE TITLE
ImportError: cannot import name ReferencePattern

### ISSUE THREAD

**Issue by noasic** [jandecaluwe/urubu-quickstart#10]
Hi, I just tried to install the quickstart on my windows machine using Python 2.7.13. I'm seeing the following error message:

```
C:\temp\urubu>python -m urubu build
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\lib\site-packages\urubu\__main__.py", line 18, in <module>
    from urubu import main
  File "C:\Python27\lib\site-packages\urubu\main.py", line 25, in <module>
    from urubu import project
  File "C:\Python27\lib\site-packages\urubu\project.py", line 33, in <module>
    from urubu import readers, processors
  File "C:\Python27\lib\site-packages\urubu\processors.py", line 31, in <module>
    from urubu import md_extensions
  File "C:\Python27\lib\site-packages\urubu\md_extensions.py", line 31, in <module>
    from markdown.inlinepatterns import ReferencePattern, REFERENCE_RE, SHORT_REF_RE
ImportError: cannot import name ReferencePattern
```

Any idea why this happens?
Thanks,
Guy.

**Comment by lkraider** [comment]
Stumbled on this, markdown version 3 added some breaking changes, you need to use version 2.6:

`pip install --upgrade 'markdown < 3' `

**Comment by Luuk34** [comment]
> Stumbled on this, markdown version 3 added some breaking changes, you need to use version 2.6:
> 
> `pip install --upgrade 'markdown < 3' `

After above:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mkdocs 1.6.1 requires markdown>=3.3.6, but you have markdown 2.6.11 which is incompatible.
mkdocs-material 9.5.46 requires markdown~=3.2, but you have markdown 2.6.11 which is incompatible.
pymdown-extensions 10.12 requires markdown>=3.6, but you have markdown 2.6.11 which is incompatible.
```

Python: 3.12.5
OS: Windows 11
